{
 "title": "project 3 frontend backend uptime and http errors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "frontend uptime in % over 24h",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{service=\"frontend-service\", instance=\"10.42.0.170:8080\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend 2xx ok: sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"2..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend 4xx error: sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"4..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "frontend 5xx error: sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"5..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"frontend-service\", status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend uptime in % over 24h",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{service=\"backend-service\", instance=\"10.42.0.166:8080\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend 2xx ok: sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"2..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend 4xx error: sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"4..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend 5xx error: sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"5..\"}[5m]))",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 5, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}