apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: observability
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80